<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>7f497b6e-efb4-4c88-8e4c-86f5126c4a9d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseAiAssistant.Application\EnterpriseAiAssistant.Application.csproj" />
    <ProjectReference Include="..\EnterpriseAiAssistant.Infrastructure\EnterpriseAiAssistant.Infrastructure.csproj" />
  </ItemGroup>

</Project>
